version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: .env
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGODB_INITDB_DATABASE: ${DB_NAME}
    ports:
      - 27017:27017
