name: Jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '24 21 * * 4'

jobs:
    jest_run:
        name: run jest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Jest
            working-directory: ./server
            run: |
              npm install
              
          - name: Run Jest
            working-directory: ./server
            run: npm test
        
    jest_coverage:
        name: run jest coverage
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Jest
            working-directory: ./server
            run: |
                npm install

          - name: Run Jest Coverage
            working-directory: ./server
            run: npm run coverage
