name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

env:
  # DB Connection
  DB_HOST: mongodb
  DB_NAME: roadwatch
  DB_USER: root
  DB_PASSWORD: password
  DB_PORT: 27017

jobs:
    jest_run:
        name: run jest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Jest
            working-directory: ./server
            run: |
              npm install

          - name: Set up Docker instance
            working-directory: ./server
            run: docker compose up

          - name: Start up Server
            working-directory: ./server
            run: npm run start
              
          - name: Run Jest Test
            working-directory: ./server
            run: npm test

          - name: Run Jest Coverage
            working-directory: ./server
            run: npm run coverage
    
    vitest_run:
        name: run vitest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Vitest
            working-directory: ./client
            run: |
              npm install
              
          - name: Run Vitest Test
            working-directory: ./client
            run: npm test

          - name: Run Vitest Coverage
            working-directory: ./client
            run: npm run coverage
            