name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
    docker:
        # This job will create a docker instance, so that it can be used when jest is run
        name: create docker 
        runs-on: ubuntu-latest
        timeout-minutes: 1  # can be changed later
        continue-on-error: true
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Create env
            working-directory: ./server
            run: |
              touch .env
              echo NODE_ENV=development>> .env
              echo PORT=3000>> .env
              echo DB_HOST=mongodb>> .env
              echo DB_NAME=roadwatch>> .env
              echo DB_USER=root>> .env
              echo DB_PASSWORD=password>> .env
              echo DB_PORT=27017>> .env
              echo JWT_SECRET=secret>> .env
              echo JWT_EXPIRES_IN=24hr>> .env
              cat .env

          - name: Set up Docker instance
            working-directory: ./server
            run: docker-compose up

    server_start:
      name: start server
      runs-on: ubuntu-latest
      timeout-minutes: 1  # can be changed later
      continue-on-error: true
      permissions:
          contents: read
          security-events: write
          actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Create env
          working-directory: ./server
          run: |
            touch .env
            echo NODE_ENV=development>> .env
            echo PORT=3000>> .env
            echo DB_HOST=mongodb>> .env
            echo DB_NAME=roadwatch>> .env
            echo DB_USER=root>> .env
            echo DB_PASSWORD=password>> .env
            echo DB_PORT=27017>> .env
            echo JWT_SECRET=secret>> .env
            echo JWT_EXPIRES_IN=24hr>> .env
            echo NOTIFICATION_PUBLIC_KEY=BIQ8FWqgNZtyxHeCALbruZO8ttzxza2xT4BeNM2E4Ix9HYeAVwVDRkHWdzNqJTdhDj21uryLKRKJpOBhqnhUEr0>> .env
            echo NOTIFICATION_PRIVATE_KEY=RBd7U-nIzTpLq-5EiPQ9VKJJiRBOBt3OuoChrLVKTNQ>> .env
            cat .env

        - name: Install Jest
          working-directory: ./server
          run: |
            npm install

        - name: Start up Server
          working-directory: ./server
          run: npm run start

    jest_run:
        name: run jest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Create env
            working-directory: ./server
            run: |
              touch .env
              echo NODE_ENV=development>> .env
              echo LIVE_SITE=https://cs472-roadwatch.vercel.app/>> .env
              echo PORT=3000>> .env
              echo DB_HOST=mongodb>> .env
              echo DB_NAME=roadwatch>> .env
              echo DB_USER=root>> .env
              echo DB_PASSWORD=password>> .env
              echo DB_PORT=27017>> .env
              echo JWT_SECRET=secret>> .env
              echo JWT_EXPIRES_IN=24hr>> .env
              echo NOTIFICATION_PUBLIC_KEY=BIQ8FWqgNZtyxHeCALbruZO8ttzxza2xT4BeNM2E4Ix9HYeAVwVDRkHWdzNqJTdhDj21uryLKRKJpOBhqnhUEr0>> .env
              echo NOTIFICATION_PRIVATE_KEY=RBd7U-nIzTpLq-5EiPQ9VKJJiRBOBt3OuoChrLVKTNQ>> .env
              cat .env

          - name: Install Jest
            working-directory: ./server
            run: |
              npm install
              
          - name: Run Jest Test
            working-directory: ./server
            run: npm test

          - name: Run Jest Coverage
            working-directory: ./server
            run: npm run coverage
          
          - name: Turn off Docker instance
            working-directory: ./server
            run: docker-compose down
    
    vitest_run:
        name: run vitest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Vitest
            working-directory: ./client
            run: |
              npm install
              
          - name: Run Vitest Test
            working-directory: ./client
            run: npm test

          - name: Run Vitest Coverage
            working-directory: ./client
            run: npm run coverage
            