name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
    docker:
        # This job will create a docker instance, so that it can be used when jest is run
        name: create docker 
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Create env
            working-directory: ./server
            run: |
              touch .env
              echo NODE_ENV=development >> .env
              echo DB_HOST=mongodb >> .env
              echo DB_NAME=roadwatch >> .env
              echo DB_USER=root >> .env
              echo DB_PASSWORD=password >> .env
              echo DB_PORT=27017 >> .env
              echo JWT_SECRET=secret >> .env
              echo JWT_EXPIRES_IN=24hr >> .env
              echo NOTIFICATION_PUBLIC_KEY=BHC05EkGYKU74-rDAMYw2lBgFA1U9ZfzHmGcSdBMZKkZ1kFJUPVTsoAHhqVq1nyFJvmPQ7XSYXoyT2SwZXDYzqk >> .env
              echo NOTIFICATION_PRIVATE_KEY=hQOr5n5Z88_iIblL4y0zdYVC6pMGCL7ZKH7RbRA0DhsDB >> .env
              cat .env

          - name: Set up Docker instance
            working-directory: ./server
            run: docker-compose up

    jest_run:
        name: run jest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Jest
            working-directory: ./server
            run: |
              npm install

          - name: Start up Server
            working-directory: ./server
            run: npm run start
              
          - name: Run Jest Test
            working-directory: ./server
            run: npm test

          - name: Run Jest Coverage
            working-directory: ./server
            run: npm run coverage
          
          - name: Turn off Docker instance
            working-directory: ./server
            run: docker-compose down
    
    vitest_run:
        name: run vitest
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install Vitest
            working-directory: ./client
            run: |
              npm install
              
          - name: Run Vitest Test
            working-directory: ./client
            run: npm test

          - name: Run Vitest Coverage
            working-directory: ./client
            run: npm run coverage
            